{
    "metadata": {
        "kernelspec": {
            "name": "SQL",
            "display_name": "SQL",
            "language": "sql"
        },
        "language_info": {
            "name": "sql",
            "version": ""
        }
    },
    "nbformat_minor": 2,
    "nbformat": 4,
    "cells": [
        {
            "cell_type": "code",
            "source": [
                "CREATE TABLE Ugyfel \n",
                "(LOGIN VARCHAR(50) PRIMARY KEY,\n",
                "EMAIL VARCHAR(100) MASKED WITH (FUNCTION = 'email()'),\n",
                "NEV VARCHAR(100) MASKED WITH (FUNCTION = 'partial(1,\"XXX\",1)'),\n",
                "SZULEV INT MASKED WITH (FUNCTION = 'random(1950,2000)'),\n",
                "NEM VARCHAR(1) MASKED WITH (FUNCTION = 'default()'),\n",
                "CIM VARCHAR(255) MASKED WITH (FUNCTION = 'default()'));\n",
                "INSERT INTO Ugyfel (LOGIN,EMAIL, NEV, SZULEV, NEM, CIM) \n",
                "VALUES \n",
                " ('adam1','ádám.kiss@mail.hu','Kiss Ádám','1991','F','5630 Békés, Szolnoki út 8.'), \n",
                " ('adam3','adam3@gmail.com','Barkóci Ádám','1970','F','3910 Tokaj, Dózsa György utca 37.'), \n",
                " ('adam4','ádám.bieniek@mail.hu','Bieniek Ádám','1976','F','8630 Balatonboglár, Juhászföldi út 1.'), \n",
                " ('agnes','agnes@gmail.com','Lengyel Ágnes','1979','N','5200 Törökszentmiklós, Deák Ferenc út 5.'), \n",
                " ('agnes3','agnes3@gmail.com','Hartyánszky Ágnes','1967','N','6430 Bácsalmás, Posta köz 2.'), \n",
                " ('AGNESH','AGNESH@gmail.com','Horváth Ágnes','1981','N','8200 Veszprém, Rákóczi utca 21.'), \n",
                " ('AGNESK','AGNESK@gmail.com','Kovács Ágnes','1988','N','1084 Budapest, Endrődi Sándor utca 47.'), \n",
                " ('akos','ákos.bíró@mail.hu','Bíró Ákos','1982','F','9023 Győr, Kossuth Lajos utca 47/b.'), \n",
                " ('aladar','aladár.dunai@mail.hu','Dunai Aladár','1980','F','5931 Nagyszénás, Árpád utca 23.'), \n",
                " ('alexandra','alexandra.bagóczki@mail.hu','Bagóczki Alexandra','1992','N','2381 Táborfalva, Petőfi utca 1/2.'), \n",
                " ('alexis','alexbiro@gmail.com','Biró Alexander','2000','F','6914 Pitvaros, Deák F. u. 38.'), \n",
                " ('andi','andrea.maródi@mail.hu','Maródi Andrea','1968','N','5465 Cserkeszőlő, Árpád utca 4.'), \n",
                " ('andras2','andrás.tóth@mail.hu','Tóth András','1997','F','4071 Egyek, Petőfi utca 30.'), \n",
                " ('andras21','andrás.molnár@mail.hu','Molnár András','1977','F','7900 Szigetvár, Rákóczi utca 67.'), \n",
                " ('andras3','andrás.vígh@mail.hu','Vígh András','1971','F','1118 Budapest, Arany János utca 1.'), \n",
                " ('andras4','andras4@gmail.com','Back András','1984','F','3783 Edelény, Fő út 169.'), \n",
                " ('andras41','andras41@gmail.com','Komjáti András','1997','F','5065 Nagykörű, Kossuth út 24.'), \n",
                " ('ANDRASE','ANDRASE@gmail.com','Erdei András','1997','F','5071 Besenyszög, Szolnoki út 8.'), \n",
                " ('ANDRASN','andrás.nagy@mail.hu','Nagy András','1980','F','6500 Baja, Fő út 169.'), \n",
                " ('andrea','andrea.kiss@mail.hu','Kiss Andrea','1993','N','1113 Budapest, Petőfi Sándor utca 87.'), \n",
                " ('andrea3','andrea3@gmail.com','Szomor Andrea','1996','N','7960 Sellye, Bécsi utca 82.'), \n",
                " ('andrea4','andrea4@gmail.com','Neizer Andrea','1981','N','1124 Budapest, Kiss u. 8.'), \n",
                " ('ANDREAT','ANDREAT@gmail.com','Tornyos Andrea','1986','N','6131 Szank, Bécsi utca 82.'), \n",
                " ('anett3','anett.pivarcsi@mail.hu','Pivarcsi Anett','1967','N','1149 Budapest, Fő út 60.'), \n",
                " ('aniko','aniko@gmail.com','Tóth Anikó','1973','N','2085 Pilisvörösvár, Deák Ferenc út 5.'), \n",
                " ('aniko4','aniko4@gmail.com','Böröcz Anikó','1978','N','2484 Agárd, Petőfi Sándor tér 1.'), \n",
                " ('ANIKOS','ANIKOS@gmail.com','Simon Anikó','1988','N','5137 Jászkisér, Bécsi utca 82.'), \n",
                " ('anita','anita.hamvay-kovács@mail.hu','Hamvay-Kovács Anita','1971','N','7220 Sarkad, Táncsics utca 19.'), \n",
                " ('annamaria1','annamária.szűcs@mail.hu','Szűcs Annamária','1990','N','1191 Budapest, Rendeki utca 21.'), \n",
                " ('ANNAMARIAR','ANNAMARIAR@gmail.com','Regős Annamária','1977','N','8283 Káptalantóti, Petőfi Sándor tér 1.'), \n",
                " ('aron2','aron2@gmail.com','Jakab Áron','1971','F','7133 Fadd, Bajcsy-Zsilinszky utca 4.'), \n",
                " ('ARONK','áron.kelemen@mail.hu','Kelemen Áron','1989','F','8200 Veszprém, Petőfi utca 8.'), \n",
                " ('arpad2','árpád.ötvös@mail.hu','Ötvös Árpád','1990','F','2600 Vác, Padragi út 158.'), \n",
                " ('ARPADH','árpád.horváth@mail.hu','Horváth Árpád','1990','F','7349 Szászvár, Dózsa György u. 1.'), \n",
                " ('ARPADM','árpád.móricz@mail.hu','Móricz Árpád','1986','F','3910 Tokaj, Rákóczi utca 67.'), \n",
                " ('attila','attila@gmail.com','Csóti Attila','1979','F','3000 Hatvan, Bajcsy-Zsilinszky utca 4.'), \n",
                " ('attila1','attila.gulyás@mail.hu','Gulyás Attila','1982','F','3881 Abaújszántó, Szolnoki út 8.'), \n",
                " ('attila4','attila.baróti@mail.hu','Baróti Attila','1975','F','7149 Báta, Arany János utca 3.'), \n",
                " ('ATTILAO','ATTILAO@gmail.com','Opra Attila','1995','F','8283 Káptalantóti, Rákóczi út 200.'), \n",
                " ('balazs1','balázs.bozsik@mail.hu','Bozsik Balázs','1992','F','2300 Ráckeve, Bécsi utca 82.'), \n",
                " ('balazs2','balázs.szűcs@mail.hu','Szűcs Balázs','1984','F','3170 Szécsény, Szabadság utca 95.'), \n",
                " ('balazs3','balazs3@gmail.com','Bakódy Balázs','1986','F','2131 Göd, Arany János utca 1.'), \n",
                " ('balint','balint@gmail.com','Horváth Bálint','1996','F','6646 Tömörkény, Endrődi Sándor utca 47.'), \n",
                " ('balint1','balint1@gmail.com','Molnár Bálint','1989','F','9181 Kimle, Fő út 169.'), \n",
                " ('balint2','balint2@gmail.com','Vukasinovity Bálint','1997','F','2330 Dunaharaszti, Béke utca 7.'), \n",
                " ('balu','bálint.endresz@mail.hu','Endresz Bálint','1976','F','3973 Cigánd, Fő út 169.'), \n",
                " ('beata4','beáta.bagi@mail.hu','Bagi Beáta','1994','N','8477 Tüskevár, Felszabadulás utca 32.'), \n",
                " ('BEATRIXK','beatrix.kerényi@mail.hu','Kerényi Beatrix','1972','N','7396 Magyarszék, Kossuth Lajos utca 47/b.'), \n",
                " ('BEATRIXS','beatrix.szekendi@mail.hu','Szekendi Beatrix','1981','N','4060 Balmazújváros, Jászai tér 21.'), \n",
                " ('BELAF','BELAF@gmail.com','Farkas Béla','1995','F','5530 Vésztő, Petőfi Sándor utca 3.'), \n",
                " ('bence','bence@gmail.com','Győrffy Bence','1987','F','6900 Makó, Árpád utca 23.'), \n",
                " ('BENCEB','bence.bajusz@mail.hu','Bajusz Bence','1973','F','8391 Sármellék, Fő utca 56.'), \n",
                " ('bernadett1','bernadett1@gmail.com','Simon Bernadett','1984','N','2300 Ráckeve, Fő utca 108.'), \n",
                " ('bernadett2','bernadett.kovács@mail.hu','Kovács Bernadett','1996','N','4200 Hajdúszoboszló, Fő út 122.'), \n",
                " ('BERNADETTO','bernadett.orbán@mail.hu','Orbán Bernadett','1987','N','5085 Rákóczifalva, Arany János utca 1.'), \n",
                " ('bertalan','bertalan@gmail.com','Csiger Bertalan','1977','F','1192 Budapest, Fő út 169.'), \n",
                " ('brigitta','brigitta.székely@mail.hu','Székely Brigitta','1978','N','2462 Martonvásár, Fő utca 47.'), \n",
                " ('brigitta3','brigitta.pataki@mail.hu','Pataki Brigitta','1991','N','2730 Albertirsa, Rendeki utca 21.'), \n",
                " ('csongor3','csongor.nagymihály@mail.hu','Nagymihály Csongor','1984','F','9181 Kimle, Deák Ferenc út 5.'), \n",
                " ('dani','daniel@gmail.com','Vörös Dániel','1986','F','7150 Bonyhád, Dózsa György u. 1.'), \n",
                " ('daniel','dániel.rácz@mail.hu','Rácz Dániel','1978','F','9181 Kimle, Szabadság tér 9.'), \n",
                " ('daniel1','dániel.keszler@mail.hu','Keszler Dániel','1969','F','3580 Tiszaújváros, Kossuth Lajos utca 6.'), \n",
                " ('david','david@gmail.com','Ambrus Dávid','1974','F','1149 Budapest, Fő út 18.'), \n",
                " ('david1','david1@gmail.com','Sobják Dávid','1970','F','5083 Kengyel, Arany János utca 3.'), \n",
                " ('david4','david4@gmail.com','Berta Dávid','1990','F','3500 Miskolc, Balatoni út 12.'), \n",
                " ('debora','debóra.barna@mail.hu','Barna Debóra','1976','N','1155 Budapest, Fő út 169.'), \n",
                " ('denes','denes@gmail.com','Tömböly Dénes','1975','F','2400 Dunaújváros, Kossuth út 39.'), \n",
                " ('desdemona','mor.otto@mail.hu','Mór Ottó','1968','F','9200 Mosonmagyaróvár Fő u. 12.'), \n",
                " ('dora3','dóra.sarodi@mail.hu','Sarodi Dóra','1995','N','2855 Bokod, Fő út 18.'), \n",
                " ('edit','edit.bittmann@mail.hu','Bittmann Edit','1984','N','6077 Orgovány, Fő utca 60.'), \n",
                " ('emese','emese.kuruc@mail.hu','Kuruc Emese','1989','N','6700 Szeged, Rákóczi utca 67.'), \n",
                " ('eszter','eszter.molnár@mail.hu','Molnár Eszter','1987','N','6800 Hódmezővásárhely, Fő út 77.'), \n",
                " ('eszter2','eszter.balogh@mail.hu','Balogh Eszter','1998','N','6760 Kistelek, Kossuth utca 11.'), \n",
                " ('eszter4','eszter.fülöp@mail.hu','Fülöp Eszter','1993','N','3643 Dédestapolcsány, Kossuth Lajos utca 47/b.'), \n",
                " ('ESZTERE','eszter.érsek@mail.hu','Érsek Eszter','1978','N','6785 Pusztamérges, Kossuth Lajos utca 6.'), \n",
                " ('eva','eva@gmail.com','Enyedi Éva','1967','N','4231 Bököny, Petőfi utca 8.'), \n",
                " ('eva2','eva2@gmail.com','Perlinger Éva','1971','N','9653 Répcelak, Bécsi utca 82.'), \n",
                " ('EVAV','EVAV@gmail.com','Viktor Éva','1980','N','6913 Csanádpalota, Arany János utca 3.'), \n",
                " ('ferenc1','ferenc.orosz@mail.hu','Orosz Ferenc','1983','F','5061 Tiszasüly, Arany János utca 3.'), \n",
                " ('fruzsina4','fruzsina4@gmail.com','Frank Fruzsina','1996','N','9700 Szombathely, Szabadság utca 95.'), \n",
                " ('gabor1','gabor1@gmail.com','Köves Gábor','1973','F','6762 Sándorfalva, Árpád utca 23.'), \n",
                " ('gabor4','gábor.telek@mail.hu','Telek Gábor','1987','F','9071 Görbeháza, Fő út 169.'), \n",
                " ('GABORS','GABORS@gmail.com','Szöllősi Gábor','1990','F','3630 Putnok, Kossuth utca 27.'), \n",
                " ('gabriella1','gabriella1@gmail.com','Nagy Gabriella','1982','N','1077 Budapest, Dob utca 1'), \n",
                " ('gabriella10','gabriella10@gmail.com','Vida Gabriella','1969','N','2484 Agárd, Arany János utca 3.'), \n",
                " ('georgij','georgij.nyíri@mail.hu','Nyíri Georgij','1983','F','8391 Sármellék, Grassalkovich út 10.'), \n",
                " ('gusztav','gusztav@gmail.com','Bárci Gusztáv','1967','F','3643 Dédestapolcsány, Endrődi Sándor utca 47.'), \n",
                " ('GYONGYIK','gyöngyi.kornseé@mail.hu','Kornseé Gyöngyi','1974','N','8800 Nagykanizsa, Fő út 60.'), \n",
                " ('GYORGYO','GYORGYO@gmail.com','Oroszi György','1980','F','7220 Sarkad, Dózsa György u. 1.'), \n",
                " ('henrik3','henrik.nádudvari@mail.hu','Nádudvari Henrik','1986','F','1077 Budapest, Tanácsköztársaság tér 1.'), \n",
                " ('IBOLYAA','ibolya.andor@mail.hu','Andor Ibolya','1983','N','9023 Győr, Posta köz 2.'), \n",
                " ('ilona3','ilona3@gmail.com','Bosnyák Ilona','1990','N','2483 Gárdony, Posta köz 2.'), \n",
                " ('imre','imre.búza@mail.hu','Búza Imre','1988','F','9181 Kimle, Petőfi Sándor tér 1.'), \n",
                " ('imre1','imre.papp@mail.hu','Papp Imre','1976','F','1077 Budapest, Szolnoki út 8.'), \n",
                " ('istvan','istvan@gmail.com','Soós István','1986','F','2370 Dabas, Kossuth utca 27.'), \n",
                " ('istvan1','istván.vizi@mail.hu','Vizi István','1997','F','7086 Ozora, Rákóczi utca 1.'), \n",
                " ('ISTVANV','ISTVANV@gmail.com','Varga István','1989','F','6320 Solt, Hősök tere 11.'), \n",
                " ('janos3','janos3@gmail.com','Harangozó János','1967','F','8700 Marcali, Petőfi Sándor tér 1.'), \n",
                " ('JANOSG','JANOSG@gmail.com','Giliga János','1975','F','3300 Eger, Deák Ferenc út 5.'), \n",
                " ('JANOSP','JANOSP@gmail.com','Pálinkás János','1984','F','5920 Csorvás, Padragi út 158.'), \n",
                " ('jozsef','jozsef@gmail.com','Gergely József','1985','F','6050 Lajosmizse, Fő út 18.'), \n",
                " ('jozsef2','józsef.vajda@mail.hu','Vajda József','1978','F','6700 Szeged, Baracsi László utca 14.'), \n",
                " ('JOZSEFG','józsef.gyuris@mail.hu','Gyuris József','1975','F','2660 Balassagyarmat, Petőfi utca 1/2.'), \n",
                " ('JUDITH','JUDITH@gmail.com','Hídasi Judit','1997','N','2100 Gödöllő, Fő út 169.'), \n",
                " ('julia','julia@gmail.com','Tóth Júlia','1993','N','5310 Kisújszállás, Árpád utca 4.'), \n",
                " ('julia4','julia4@gmail.com','Nagy Júlia','1985','N','7000 Sárbogárd, Jászai tér 21.'), \n",
                " ('julianna4','julianna4@gmail.com','Szabó Julianna','1990','N','6700 Szeged, Kossuth Lajos utca 6.'), \n",
                " ('kanita12','anita.kiss12@gmail.com','Kiss Anita','1975','N','2230 Gyömrő Fő tér 3.'), \n",
                " ('kata','katalin.gondos@mail.hu','Gondos Katalin','1968','N','8237 Tihany, Kossuth Lajos utca 6.'), \n",
                " ('katalin','katalin.horváth@mail.hu','Horváth Katalin','1968','N','2424 Előszállás, Rákóczi út 200.'), \n",
                " ('katalin4','katalin4@gmail.com','Kertész Katalin','1986','N','2800 Tatabánya, Búvár utca 4.'), \n",
                " ('kati','katalin.zatykó@mail.hu','Zatykó Katalin','1995','N','7511 Ötvöskónyi, Kossuth Lajos utca 6.'), \n",
                " ('katka','katalin.kovács@mail.hu','Kovács Katalin','1975','N','8254 Kővágóörs, Petőfi utca 22.'), \n",
                " ('klaudia2','klaudia.bakó@mail.hu','Bakó Klaudia','1982','N','8254 Kővágóörs, Kossuth Lajos utca 6.'), \n",
                " ('kornel4','kornél.lukács@mail.hu','Lukács Kornél','1975','F','2053 Herceghalom, Bécsi utca 82.'), \n",
                " ('kristof4','kristof4@gmail.com','Poprádi Kristóf','1984','F','8220 Balatonalmádi, Mészáros utca 7.'), \n",
                " ('kriszti','kriszti@gmail.com','Horváth Krisztina','1978','N','6060 Tiszakécske, Árpád utca 4.'), \n",
                " ('krisztian4','krisztián.czérna@mail.hu','Czérna Krisztián','1970','F','1107 Budapest, Dózsa György utca 37.'), \n",
                " ('KRISZTIANM','KRISZTIANM@gmail.com','Mogyródi Krisztián','1968','F','9155 Lébény, Jászai tér 21.'), \n",
                " ('krisztina','krisztina@gmail.com','Szedlár Krisztina','1979','N','6646 Tömörkény, Arany János utca 1.'), \n",
                " ('krisztina1','krisztina.bori@mail.hu','Bori Krisztina','1969','N','2115 Vácszentlászló, Fő utca 47.'), \n",
                " ('KRISZTINAG','KRISZTINAG@gmail.com','Gyárfás Krisztina','1987','N','6762 Sándorfalva, Arany János utca 1.'), \n",
                " ('lajos','lajos.kiss@mail.hu','Kiss Lajos','1978','F','1077 Budapest, Dob utca 1'), \n",
                " ('lala','lajos.nagymihály@mail.hu','Nagymihály Lajos','1997','F','8638 Balatonlelle, Rákóczi út 200.'), \n",
                " ('laszlo1','lászló.farkas@mail.hu','Farkas László','1967','F','5200 Törökszentmiklós, Rendeki utca 21.'), \n",
                " ('laszlo2','lászló.móra@mail.hu','Móra László','1975','F','9970 Szentgotthárd, Petőfi utca 1/2.'), \n",
                " ('LASZLOA','lászló.antal@mail.hu','Antal László','1969','F','2484 Agárd, Bécsi utca 82.'), \n",
                " ('LASZLON','lászló.nagy@mail.hu','Nagy László','1969','F','1173 Budapest, Jászai tér 21.'), \n",
                " ('maria1','mária.baráth@mail.hu','Baráth Mária','1995','N','1047 Budapest, Posta köz 2.'), \n",
                " ('mark','márk.kispál@mail.hu','Kispál Márk','1996','F','1086 Budapest, Juhászföldi út 1.'), \n",
                " ('MARKH','márk.horváth@mail.hu','Horváth Márk','1997','F','4400 Nyíregyháza, Badacsonyi utca 12.'), \n",
                " ('marton','marton@gmail.com','Kalacsi Márton','1989','F','5137 Jászkisér, Fő út 169.'), \n",
                " ('MATEK','máté.koza@mail.hu','Koza Máté','1997','F','1011 Budapest, Központi telep 3.'), \n",
                " ('matyas2','matyas2@gmail.com','Botka Mátyás','1972','F','2700 Cegléd, Kossuth Lajos utca 6.'), \n",
                " ('MATYASS','mátyás.szilágyi@mail.hu','Szilágyi Mátyás','1975','F','9023 Győr, Kossuth Lajos utca 6.'), \n",
                " ('melissza','nagy_peter@indamail.hu','Nagy Péter','1998','F','6800 Hódmezővásárhely, Oldalkosát u. 1.'), \n",
                " ('MIHALYJ','mihály.juhász@mail.hu','Juhász Mihály','1979','F','6786 Ruzsa, Rákóczi utca 1.'), \n",
                " ('miklos2','miklos2@gmail.com','Gondos Miklós','1995','F','2100 Gödöllő, Árpád utca 23.'), \n",
                " ('MIKLOSB','miklós.balla@mail.hu','Balla Miklós','1979','F','4060 Balmazújváros, Szent István utca 2.'), \n",
                " ('MONIKAM','mónika.mohos@mail.hu','Mohos Mónika','1974','N','2241 Sülysáp, Baracsi László utca 14.'), \n",
                " ('NANDORF','nándor.fő@mail.hu','Fő Nándor','1968','F','5920 Csorvás, Bécsi utca 82.'), \n",
                " ('nikolett3','nikolett3@gmail.com','Horváth Nikolett','1981','N','1072 Budapest, Arany János utca 1.'), \n",
                " ('nikoletta4','nikoletta4@gmail.com','Kő Nikoletta','1972','N','5537 Zsadány, Fő út 18.'), \n",
                " ('NIKOLETTAT','nikoletta.tatár@mail.hu','Tatár Nikoletta','1997','N','1067 Budapest, Győri utca 12.'), \n",
                " ('norbert','norbert@gmail.com','Szűcs Norbert','1969','F','5071 Besenyszög, Győri utca 12.'), \n",
                " ('norbert2','norbert.hegedűs@mail.hu','Hegedűs Norbert','1991','F','2081 Piliscsaba, Rendeki utca 21.'), \n",
                " ('norbert4','norbert4@gmail.com','Mile Norbert','1983','F','3973 Cigánd, Bajcsy-Zsilinszky utca 4.'), \n",
                " ('norbert5','norbert5@gmail.com','Béres Norbert','1975','F','8640 Fonyód, Bajcsy-Zsilinszky utca 4.'), \n",
                " ('pal','pál.barabás@mail.hu','Barabás Pál','1968','F','1183 Budapest, Szolnoki út 8.'), \n",
                " ('peter1','peter1@gmail.com','Kozma Péter','1976','F','6913 Csanádpalota, Központi telep 3.'), \n",
                " ('peter2','peter2@gmail.com','Bozsó Péter','1976','F','4800 Vásárosnamény, Zombori út 2/A'), \n",
                " ('peter3','peter3@gmail.com','Szalai Péter','1983','F','1155 Budapest, Arany János utca 3.'), \n",
                " ('peter4','péter.bíró@mail.hu','Bíró Péter','1985','F','5137 Jászkisér, Rákóczi utca 67.'), \n",
                " ('PETERB','péter.berendi@mail.hu','Berendi Péter','1969','F','3980 Sátoraljaújhely, Vasút utca 4/10.'), \n",
                " ('polla','polla@gmail.com','Palágyi Polla','1994','N','2484 Agárd, Fő út 18.'), \n",
                " ('rajmond4','rajmond.rácz@mail.hu','Rácz Rajmond','1993','F','9155 Lébény, Petőfi utca 1/2.'), \n",
                " ('reka4','réka.szikszai@mail.hu','Szikszai Réka','1969','N','8254 Kővágóörs, Templom utca 73.'), \n",
                " ('RENATAK','renáta.kardos@mail.hu','Kardos Renáta','1988','N','7086 Ozora, Bécsi utca 82.'), \n",
                " ('RENATAS','RENATAS@gmail.com','Szirmai Renáta','1991','N','2053 Herceghalom, Kossuth utca 27.'), \n",
                " ('robert2','robert2@gmail.com','Patay Róbert','1977','F','2370 Dabas, Rákóczi utca 21.'), \n",
                " ('ROBERTI','róbert.iván@mail.hu','Iván Róbert','1967','F','2377 Örkény, Petőfi Sándor utca 3.'), \n",
                " ('ROBERTP','ROBERTP@gmail.com','Pásztor Róbert','1972','F','5137 Jászkisér, Ady Endre út 27.'), \n",
                " ('roland','roland@gmail.com','Tóth Roland','1968','F','2000 Szentendre, Fő út 169.'), \n",
                " ('roland1','roland.ferencz@mail.hu','Ferencz Roland','1985','F','2424 Előszállás, Fő út 169.'), \n",
                " ('roza2','roza2@gmail.com','Bucskó Róza','1988','N','5661 Újkígyós, Arany János utca 3.'), \n",
                " ('sandor','sandor@gmail.com','Karasz Sándor','1970','F','8283 Káptalantóti, Kossuth Lajos utca 1/a.'), \n",
                " ('sandor3','sándor.farkas@mail.hu','Farkas Sándor','1989','F','8640 Fonyód, Tanácsköztársaság tér 1.'), \n",
                " ('sandor4','sandor4@gmail.com','Nagy Sándor','1997','F','4600 Kisvárda, Fő utca 47.'), \n",
                " ('sara','sára.farkas@mail.hu','Farkas Sára','1973','N','5940 Tótkomlós, Felszabadulás utca 32.'), \n",
                " ('SEBASTIANF','SEBASTIANF@gmail.com','Foltényi Sebastián','1992','F','7960 Sellye, Grassalkovich út 10.'), \n",
                " ('sebestyen','sebestyen@gmail.com','Rab Sebestyén','1992','F','7130 Tolna, Központi telep 3.'), \n",
                " ('szabolcs','szabolcs.bodor@mail.hu','Bodor Szabolcs','1990','F','6786 Ruzsa, Ady Endre út 27.'), \n",
                " ('SZABOLCSM','szabolcs.miklós@mail.hu','Miklós Szabolcs','1980','F','1102 Budapest, Fő út 169.'), \n",
                " ('SZILARDS','szilárd.szalai@mail.hu','Szalai Szilárd','1967','F','1077 Budapest, Fő út 18.'), \n",
                " ('szilvia1','szilvia.tari@mail.hu','Tari Szilvia','1971','N','6080 Szabadszállás, Bécsi utca 82.'), \n",
                " ('tamara2','tamara.miklós@mail.hu','Miklós Tamara','1980','N','3910 Tokaj, Kossuth út 39.'), \n",
                " ('tamas','tamás.antal@mail.hu','Antal Tamás','1984','F','4440 Tiszavasvári, Posta köz 2.'), \n",
                " ('TAMASF','TAMASF@gmail.com','Fényes Tamás','1997','F','9023 Győr, Arany János utca 1.'), \n",
                " ('tibor','tibor.gombos@mail.hu','Gombos Tibor','1993','F','7100 Szekszárd, Kossuth utca 77.'), \n",
                " ('tibor2','tibor2@gmail.com','Dániel Tibor','1985','F','6646 Tömörkény, Árpád utca 23.'), \n",
                " ('tihamer','tihamér.kazy@mail.hu','Kazy Tihamér','1991','F','2370 Dabas, Fő utca 60.'), \n",
                " ('timea','timea@gmail.com','Papós Tímea','1996','N','1035 Budapest,  Kossuth út 77.'), \n",
                " ('timea2','tímea.dusha@mail.hu','Dusha Tímea','1975','N','5920 Csorvás, Kossuth utca 8.'), \n",
                " ('tunde','tunde@gmail.com','Turcsik Tünde','1974','N','7130 Tolna, Fő út 122.'), \n",
                " ('valentin','valentin.feró@mail.hu','Feró Valentin','1986','F','3895 Gönc, Búvár utca 4.'), \n",
                " ('veronika4','veronika4@gmail.com','Tankó Veronika','1983','N','6412 Balotaszállás, Rendeki utca 21.'), \n",
                " ('VIKTORIAU','viktoria.urbán@mail.hu','Urbán Viktoria','1996','N','3860 Encs, Népboltsor  2.'), \n",
                " ('VIKTORK','viktor.keresztúri@mail.hu','Keresztúri Viktor','1989','F','2532 Tokodaltáró, Nagy Lajos tér 4.'), \n",
                " ('vivien3','vivien3@gmail.com','Boros Vivien','1991','N','2117 Isaszeg, Fő út 122.'), \n",
                " ('zoltan','zoltán.fodor@mail.hu','Fodor Zoltán','1979','F','3441 Mezőkeresztes, Fő utca 23.'), \n",
                " ('zoltan4','zoltan4@gmail.com','Barna Zoltán','1986','F','8313 Balatongyörök, Jászai tér 21.'), \n",
                " ('ZOLTANP','zoltán.pintér@mail.hu','Pintér Zoltán','1977','F','6050 Lajosmizse, Fő út 18.'), \n",
                " ('ZOLTANT','zoltán.tóth@mail.hu','Tóth Zoltán','1985','F','4244 Újfehértó, Posta köz 2.'), \n",
                " ('zsofi1','zsofi1@gmail.com','Molnár Zsófi','1983','N','2730 Albertirsa, Árpád utca 23.'), \n",
                " ('zsolt1','zsolt.pulai@mail.hu','Pulai Zsolt','1988','F','8391 Sármellék, Fő utca 60.'), \n",
                " ('ZSOLTJ','ZSOLTJ@gmail.com','Józsa Zsolt','1983','F','8315 Gyenesdiás, Bajcsy-Zsilinszky utca 4.'), \n",
                " ('zsuzsa','zsuzsanna@gmail.com','Pusztai Zsuzsanna','1980','N','6783 Ásotthalom, Badacsonyi utca 12.'), \n",
                " ('zsuzsa3','zsuzsa.varsányi@mail.hu','Varsányi Zsuzsa','1979','N','8600 Siófok, Árpád utca 4.'), \n",
                " ('zsuzsanna','zsuzsanna.barta@mail.hu','Barta Zsuzsanna','1994','N','4172 Biharnagybajom, Dózsa György utca 37.'), \n",
                " ('ZSUZSAV','zsuzsa.vajda@mail.hu','Vajda Zsuzsa','1976','N','6786 Ruzsa, Kossuth utca 77.');\n",
                "\n",
                "CREATE USER MaskUser WITHOUT Login;\n",
                "GRANT SELECT ON #Ugyfel TO MaskUser\n",
                "\n",
                "EXECUTE AS User= 'MaskUser';\n",
                "SELECT * FROM #Ugyfel\n",
                "REVERT"
            ],
            "metadata": {
                "azdata_cell_guid": "f784e580-575c-481e-b3ee-8ccca057b2c1",
                "language": "sql"
            },
            "outputs": [
                {
                    "output_type": "error",
                    "ename": "",
                    "evalue": "Msg 262, Level 14, State 1, Line 1\nCREATE TABLE permission denied in database 'webshop'.",
                    "traceback": []
                },
                {
                    "output_type": "display_data",
                    "data": {
                        "text/html": "Total execution time: 00:00:00.039"
                    },
                    "metadata": {}
                }
            ],
            "execution_count": 9
        }
    ]
}